### PR TITLE
backport xrootd from 81x

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@bbockelm , root in 74X failed to compile using xrootd 4.4.1. The build error is 

```
/build/cmsbuild/jenkins-workarea/workspace/cmsdist-test-pr/testBuildDir/BUILD/slc6_amd64_gcc491/lcg/root/6.02.00-cms5/root-6.02.00/net/netxng/src/TNetXNGFile.cxx: In member function 'virtual Bool_t TNetXNGFile::GetVectorReadLimits()':
/build/cmsbuild/jenkins-workarea/workspace/cmsdist-test-pr/testBuildDir/BUILD/slc6_amd64_gcc491/lcg/root/6.02.00-cms5/root-6.02.00/net/netxng/src/TNetXNGFile.cxx:699:26: error: 'class XrdCl::File' has no member named 'GetDataServer'
```
