### PR TITLE
updated das_client and scram

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@vkuznet , looks like new das client does not work with python 2.6.4

```
Traceback (most recent call last):
  File "/build/cmsbuild/jenkins-workarea/workspace/cmsdist-test-pr/testBuildDir/slc6_amd64_gcc472/cms/das_client/v03.01.00/bin/das_client.py", line 570, in <module>
    main()
  File "/build/cmsbuild/jenkins-workarea/workspace/cmsdist-test-pr/testBuildDir/slc6_amd64_gcc472/cms/das_client/v03.01.00/bin/das_client.py", line 458, in main
    jsondict = get_data(host, query, idx, limit, debug, thr, ckey, cert, capath, qcache)
  File "/build/cmsbuild/jenkins-workarea/workspace/cmsdist-test-pr/testBuildDir/slc6_amd64_gcc472/cms/das_client/v03.01.00/bin/das_client.py", line 314, in get_data
    fdesc = opener.open(req)
  File "/build/cmsbuild/jenkins-workarea/workspace/cmsdist-test-pr/testBuildDir/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/urllib2.py", line 389, in open
    response = self._open(req, data)
  File "/build/cmsbuild/jenkins-workarea/workspace/cmsdist-test-pr/testBuildDir/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/urllib2.py", line 407, in _open
    '_open', req)
  File "/build/cmsbuild/jenkins-workarea/workspace/cmsdist-test-pr/testBuildDir/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/urllib2.py", line 367, in _call_chain
    result = func(*args)
  File "/build/cmsbuild/jenkins-workarea/workspace/cmsdist-test-pr/testBuildDir/slc6_amd64_gcc472/cms/das_client/v03.01.00/bin/das_client.py", line 71, in https_open
    return self.do_open(self.get_connection, req)
  File "/build/cmsbuild/jenkins-workarea/workspace/cmsdist-test-pr/testBuildDir/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/urllib2.py", line 1099, in do_open
    h = http_class(host, timeout=req.timeout) # will parse host:port
  File "/build/cmsbuild/jenkins-workarea/workspace/cmsdist-test-pr/testBuildDir/slc6_amd64_gcc472/cms/das_client/v03.01.00/bin/das_client.py", line 79, in get_connection
    context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
AttributeError: 'module' object has no attribute 'SSLContext'
```

**Comment by davidlt** [comment]
That's Python 2.7.9+ class.

**Comment by vkuznet** [comment]
As David pointed out it is python 2.7, I thought we switch to python 2.7 a long time ago. If this is not possible to do for all CMSSW then we need yet another if-else solution which will check SSLContext and us it for specific version of python. The context was introduced to resolve CERN CA certificates issue. Let me know what CMSSW requirements are, do we need to support python 2.6 and python 2.7?

**Comment by davidlange6** [comment]
We did. 53x is nearly 5 years old by now:) lets digest the options in the next weeks.

Cheers,
David

On 25 Aug 2016, at 19:26, Valentin Kuznetsov <notifications@github.com<mailto:notifications@github.com>> wrote:

As David pointed out it is python 2.7, I thought we switch to python 2.7 a long time ago. If this is not possible to do for all CMSSW then we need yet another if-else solution which will check SSLContext and us it for specific version of python. The context was introduced to resolve CERN CA certificates issue. Let me know what CMSSW requirements are, do we need to support python 2.6 and python 2.7?

**Comment by smuzaffar** [comment]
closing this PR for now. If/When we have das_client which works with python 2.6 then we can come back to it.
For now we are fine as along as we use das_client wrapper.
