### ISSUE TITLE
Install latest Rucio client

### ISSUE THREAD

**Issue by ericvaandering** [cms-sw/cmsdist#8739]
Following #7861 and #7530 can we get the latest Rucio client installed?

For python3 this is 32.3.1 (Rucio has dropped the leading 1).

For python2, should it be needed, I believe 1.29.14 is the last supported version. 

@belforte

**Comment by smuzaffar** [comment]
@ericvaandering , `rucio-clients 32.3.1` is for `rhel9` as it requires `python 3.9` and so we can not install it on rhel8. I can deploy `1.31.7` (latest version which supports python 3.6)

**Comment by ericvaandering** [comment]
Then 1.31 should be fine until Alma/EL9 is more widely used. I don't think the client REQUIRES any feature of 3.9. But 3.6 is EOL already.

**Comment by belforte** [comment]
shall we look at living with different Rucio client versions on different OSes ?

**Comment by ericvaandering** [comment]
Fine from my side.

**Comment by belforte** [comment]
my side too. I expect transparency, if not, will put switches in CRABClient as needed.

**Comment by smuzaffar** [comment]
@ericvaandering ,  following `rucio-clients` version are now available on cvmfs

- rhel9 (python3 only): `32.3.1`
- rhel8 (python3 only): `1.31.7` (this is latest version to support system python3 3.6)
- rhel7:
  - python3: `1.31.7`
  - python2: `1.28.7`

**Comment by nikodemas** [comment]
@ericvaandering CMS monitoring started to have issues related to the new version. Copying the [issue](https://github.com/dmwm/CMSRucio/issues/626) from `CMSRucio` created by @dynamic-entropy:

**Describe the bug**

As of Oct 5, jobs using the rucio setup scripts from cvmfs started to failed with the following traceback.

```
tunikode@lxplus806 ~ $ k exec -n hdfs -it cron-size-quotas-66d6c6f5b5-mslt2 -- /bin/bash
[root@cron-size-quotas-66d6c6f5b5-mslt2 data]# python3
Python 3.9.12 (main, Aug  9 2023, 10:29:12) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> exit()
[root@cron-size-quotas-66d6c6f5b5-mslt2 data]# . /cvmfs/cms.cern.ch/rucio/setup-py3.sh
rucio 1.31.7
[root@cron-size-quotas-66d6c6f5b5-mslt2 data]# python3
Python 3.9.12 (main, Aug  9 2023, 10:29:12) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/usr/local/lib/python3.9/site-packages/pandas/core/api.py", line 47, in <module>
    from pandas.core.groupby import (
  File "/usr/local/lib/python3.9/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/usr/local/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 67, in <module>
    from pandas.core.frame import DataFrame
  File "/usr/local/lib/python3.9/site-packages/pandas/core/frame.py", line 142, in <module>
    from pandas.core.generic import (
  File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 178, in <module>
    from pandas.core.methods.describe import describe_ndframe
  File "/usr/local/lib/python3.9/site-packages/pandas/core/methods/describe.py", line 41, in <module>
    from pandas.io.formats.format import format_percentiles
  File "/usr/local/lib/python3.9/site-packages/pandas/io/formats/format.py", line 91, in <module>
    from pandas.io.common import (
  File "/usr/local/lib/python3.9/site-packages/pandas/io/common.py", line 88, in <module>
    class IOArgs:
  File "/cvmfs/cms.cern.ch/rucio/x86_64/rhel7/py3/current/lib/python3.6/site-packages/dataclasses.py", line 958, in dataclass
    return wrap(_cls)
  File "/cvmfs/cms.cern.ch/rucio/x86_64/rhel7/py3/current/lib/python3.6/site-packages/dataclasses.py", line 950, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/cvmfs/cms.cern.ch/rucio/x86_64/rhel7/py3/current/lib/python3.6/site-packages/dataclasses.py", line 800, in _process_class
    cls_fields = [_get_field(cls, name, type)
  File "/cvmfs/cms.cern.ch/rucio/x86_64/rhel7/py3/current/lib/python3.6/site-packages/dataclasses.py", line 800, in <listcomp>
    cls_fields = [_get_field(cls, name, type)
  File "/cvmfs/cms.cern.ch/rucio/x86_64/rhel7/py3/current/lib/python3.6/site-packages/dataclasses.py", line 659, in _get_field
    if (_is_classvar(a_type, typing)
  File "/cvmfs/cms.cern.ch/rucio/x86_64/rhel7/py3/current/lib/python3.6/site-packages/dataclasses.py", line 550, in _is_classvar
    return type(a_type) is typing._ClassVar
AttributeError: module 'typing' has no attribute '_ClassVar'
```

**To Reproduce**

1. Setup rucio using the cvmfs script: `source /cvmfs/cms.cern.ch/rucio/setup-py3.sh`
2. With python version > 3.6; start REPL
3. import pandas

**Expected behavior**

Should run without any error.

**Additional context**

The new installation has the `dataclass.py` file in the PYTHONPATH, backported possibly for python 3.6
But it causes problems in newer versions of Python which have the dataclass module built in.
https://docs.python.org/3/library/dataclasses.html

FYI @leggerf

**Comment by dynamic-entropy** [comment]
@smuzaffar Any suggestions? 
We still need the backported `dataclass.py` for python3.6 but not for later versions starting `3.7`.

**Comment by belforte** [comment]
this works on lxplus8 with python 3.6 (the python3 distributed with that OS). Do you really need python 3.9 ? IIUC you should be using the more recent Rucio client on Alma 9 for that. Can you give it a try ?

**Comment by smuzaffar** [comment]
Rucio installed on cvmfs assumes to use default system python. For rhel7 , it should be `3.6` and looks like you have `3.9` installed.

**Comment by dynamic-entropy** [comment]
That is true. ~It will work for python3.6 irrespective of the distribution.~
@nikodemas I would suggest you upgrade the base image of the distro or downgrade the Python version as required/easy for other tools in your pipeline.
As Stefano and Shazad point out, the installation assumes the default Python version for the distribution.

**Comment by belforte** [comment]
@nikodemas if you have your own python3 installation, you may very will simply do `pip install rucio` and then
`export RUCIO_CONFIG=/cvmfs/cms.cern.ch/rucio/x86_64/slc7/py3/current/etc/rucio.cfg`
configuration file is version independent, it is simply the name of the hosts to connect to.

FWIW I pip install Rucio that way on my Ubuntu 22.04 and it works happily with python 3.10 :-)
(that's Rucio client 1.31.4, by the way).

**Comment by nikodemas** [comment]
Thanks everyone for your help and advice - the issue is fixed.

**Comment by smuzaffar** [comment]
closing this issue. feel free to open a new one if a newer rucio version is needed
