### PR TITLE
Add GPU support for ONNXRuntime

### PR DESCRIPTION
**Pull request by hqucms**
This PR adds the GPU support for ONNXRuntime. The built library still runs on CPU by default (thus current applications in CMSSW are unaffected), while GPU inference can be enabled if needed (see [example](https://www.onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html)).

A few changes needed:
 - a small modification on `cuda` is needed (namely, keeping `libcudart_static.a`) for cmake to detect `nvcc` correctly
 - `cudnn` is added as a dependency. Note that generally downloading `cudnn` needs NVIDIA Developer Program Membership, though direct download link w/o authentication exists (and used here). Experts should probably double check if  the way we distribute it complies with its [SLA](https://docs.nvidia.com/deeplearning/cudnn/sla/index.html).

Also I am not sure if this will compile on `ppc64le` or `aarch64` (though `cudnn` exists for them).

FYI @riga @mialiu149

### CODE REVIEW

File: cuda.spec [hunk 1]
```diff
@@ -34,6 +34,7 @@ mkdir -p %{i}/lib64/stubs
 
 # package only the runtime static library
 mv %_builddir/build/lib64/libcudadevrt.a %{i}/lib64/
+mv %_builddir/build/lib64/libcudart_static.a %{i}/lib64/
```
Comment (smuzaffar) [inline cuda.spec]: any objections/concern @fwyzard ?

Comment (fwyzard) [reply cuda.spec]: Mhm... I don't think that mixing the shared and static version of `libcudart` is a good idea.
Can ONNX not use the dynamic version ?

File: cudnn.spec [hunk 2]
```diff
@@ -0,0 +1,26 @@
+### RPM external cudnn 8.1.1.33
+## INITENV +PATH LD_LIBRARY_PATH %i/lib64
+
+%define cudaver_maj 11.2
```
Comment (fwyzard) [inline cudnn.spec]: Probably just nitpicking, but this is not the "major" CUDA version.
Can you just use `cudaver` ?

Also, @smuzaffar , is there a way to get this directly from the CUDA spec file ?

File: cuda.spec [hunk 3]
```diff
@@ -101,6 +102,7 @@ ln -sf libnvidia-ptxjitcompiler.so.1                                        %{i}
 sed \
   -e"/^TOP *=/s|= .*|= $CMS_INSTALL_PREFIX/%{pkgrel}|" \
   -e's|$(_HERE_)|$(TOP)/bin|g' \
+  -e's|$(TOP)/lib|$(TOP)/lib64|g' \
```
Comment (fwyzard) [inline cuda.spec]: this looks correct, but in fact should not be needed, after scram has set up the environment ?

File: cuda.spec (hunk 1 above)
Comment (hqucms) [reply cuda.spec]: This `libcudart_static.a` is needed otherwise `enable_language(CUDA)` in cmake crashes. I don't think onnxruntime really uses it.

File: cudnn.spec (hunk 2 above)
Comment (smuzaffar) [reply cudnn.spec]: not really, This is parsed and used by cmsBuild (even before installing dependencies), so at that time cmsBuild do not know the actual value. We can use a common file ( just like https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_3_X/master/cuda-flags.file ) where one can define this version and then include it in both cuda and cudnn. But this looks very much over killed for this purpose. 

  I would suggest that in`%prep` section just check if `$CUDA_VERSION` and `%{cudaver_maj}` are same (some sed/cut/grep is needed)

Comment (fwyzard) [reply cudnn.spec]: OK, if it cannot be extracted form the CUDA spec file, better leave it hard coded here then - this way we don't need to rebuild cuDNN for minor updates to CUDA (i.e. 11.2.0 -> 11.2.1 --> 11.2.2).

I assume we'll notice soon enough if we do a update CUDA and fail to update CUDNN.

File: cuda.spec (hunk 1 above)
Comment (fwyzard) [reply cuda.spec]: why do we need cmake ?
it looks like cuDNN is not built, it's simply unpacked.

Comment (fwyzard) [reply cuda.spec]: can you set the `CUDA_USE_STATIC_CUDA_RUNTIME` cmake option to `OFF` ?

Comment (hqucms) [reply cuda.spec]: > why do we need cmake ?
> it looks like cuDNN is not built, it's simply unpacked.

We use cmake for ONNXRuntime. For cuDNN indeed it's simply unpacked.

> can you set the CUDA_USE_STATIC_CUDA_RUNTIME cmake option to OFF ?

Sure, I can try that.

Comment (hqucms) [reply cuda.spec]: @fwyzard Unfortunately `CUDA_USE_STATIC_CUDA_RUNTIME` does not make a difference. It seems it's superseded by `CMAKE_CUDA_RUNTIME_LIBRARY` now?

In fact I managed to work around this with the following lines:
```
   -DCMAKE_CUDA_FLAGS="-cudart shared" \
   -DCMAKE_CUDA_RUNTIME_LIBRARY=Shared \
   -DCMAKE_TRY_COMPILE_PLATFORM_VARIABLES="CMAKE_CUDA_RUNTIME_LIBRARY" \
```
Now we don't need `libcudart_static.a` anymore. In fact I think the really useful one is `-DCMAKE_CUDA_FLAGS="-cudart shared"`, which is sufficient to solve the problem in a newer cmake version, but somehow I need all three lines in the cmake version we use...

Also the problem is purely in cmake -- when calling `enable_language(CUDA)` it tries to compile a test program with `nvcc` and then parse the output to set up various CUDA paths/flags, and there it links to `libcudart_static.a` since the `-cudart` defaults to `static` in `nvcc`. After that stage, whether linking to cudart statically or dynamically can be controlled by `CMAKE_CUDA_RUNTIME_LIBRARY` and it's set to `Shared` [in onnxruntime](https://github.com/cms-externals/onnxruntime/blob/cms/v1.6.0/cmake/CMakeLists.txt#L1107).

File: cudnn.spec (hunk 2 above)
Comment (hqucms) [reply cudnn.spec]: OK I renamed `cudaver_maj` to `cudaver` added a check in the `%prep` section now.

**Comment by fwyzard** [comment]
nice!

**Comment by fwyzard** [comment]
please test

File: cuda.spec (hunk 3 above)
Comment (hqucms) [reply cuda.spec]: Indeed it's not really needed. I reverted all the changes on cuda.spec now.

**Comment by fwyzard** [comment]
please test for slc7_aarch64_gcc9

**Comment by fwyzard** [comment]
please test for slc7_ppc64le_gcc9

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@hqucms with these changes
  - does ONNX still run fine without a GPU ?
  - does it always use a GPU if it detects one, or does it need some runtime configuration ?

**Comment by hqucms** [comment]
> @hqucms with these changes
> 
> * does ONNX still run fine without a GPU ?

Yes.

> * does it always use a GPU if it detects one, or does it need some runtime configuration ?

No, it needs to enabled explicitly to run on GPUs.

**Comment by fwyzard** [comment]
allow @hqucms test rights

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
this
```
---> test test_py_onnxruntime had ERRORS
```
points to
```
===== Test "test_py_onnxruntime" ====
Traceback (most recent call last):
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/slc7_amd64_gcc900/external/onnxruntime/1.6.0-b578716d6932c1ae9ed96cefdf913fea/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 206, in __init__
    self._create_inference_session(providers, provider_options)
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/slc7_amd64_gcc900/external/onnxruntime/1.6.0-b578716d6932c1ae9ed96cefdf913fea/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 231, in _create_inference_session
    sess.initialize_session(providers or [], provider_options or [])
RuntimeError: /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_amd64_gcc900/external/onnxruntime/1.6.0-b578716d6932c1ae9ed96cefdf913fea/onnxruntime-1.6.0/onnxruntime/core/providers/cuda/cuda_call.cc:123 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_amd64_gcc900/external/onnxruntime/1.6.0-b578716d6932c1ae9ed96cefdf913fea/onnxruntime-1.6.0/onnxruntime/core/providers/cuda/cuda_call.cc:117 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 100: no CUDA-capable device is detected ; GPU=10947 ; hostname=cmsbuild19.cern.ch ; expr=cudaSetDevice(device_id_); 
```

From `CUDA failure 100: no CUDA-capable device is detected`, it looks like ONNX was automatically trying to use CUDA ?

**Comment by hqucms** [comment]
Looks like there is some difference between the python API and the C/C++ API. The python API prioritize the GPU backend over the CPU one, while the C/C++ API does not (thus the other test `testONNXRuntime` passes).

**Comment by hqucms** [comment]
please test with https://github.com/cms-sw/cmssw/pull/33322

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#33322 for slc7_aarch64_gcc9

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#33322 for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#33322 for slc7_ppc64le_gcc9

**Comment by hqucms** [comment]
It looks like this does not work on ppc64le or aarch64, so I changed it to build the GPU support only on x86_64.

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
please test for slc7_ppc64le_gcc9

**Comment by hqucms** [comment]
please test for slc7_aarch64_gcc9

**Comment by fwyzard** [comment]
> It looks like this does not work on ppc64le or aarch64, so I changed it to build the GPU support only on x86_64.

Do you mean from your experience with this PR, or did you also find it documentated anywhere ?
Looking at the CUDA and TensorRT pages for ONNX Runtime I didn't see any mention of them supporting (or not) any specific architecture.

**Comment by hqucms** [comment]
> > It looks like this does not work on ppc64le or aarch64, so I changed it to build the GPU support only on x86_64.
> 
> Do you mean from your experience with this PR, or did you also find it documentated anywhere ?
> Looking at the CUDA and TensorRT pages for ONNX Runtime I didn't see any mention of them supporting (or not) any specific architecture.

It was based on the PR test here. I did not find any mention of the support for ppc64le or aarch64 either...

**Comment by smuzaffar** [comment]
for ppc64le, onnxruntime failed to find `cudnn.h`. I do see that `-I/scratch/cmsbuild/jenkins_b/workspace/ib-run-pr-tests/testBuildDir/slc7_ppc64le_gcc9/external/cudnn/8.1.1.33-e758fb257eed5552a316ccde58ce7909/include` is there. Are cudnn header installed in different include path or may be there is a sub-directory?

```
/scratch/cmsbuild/jenkins_b/workspace/ib-run-pr-tests/testBuildDir/slc7_ppc64le_gcc9/external/gcc/9.3.0/bin/c++  -DEIGEN_MPL2_ONLY -DEIGEN_USE_THREADS -DENABLE_ORT_FORMAT_LOAD -DNSYNC_ATOMIC_CPP11 -DONNX_ML=1 -DONNX_NAMESPACE=onnx -DPLATFORM_POSIX -DUSE_CUDA=1 -DUSE_EIGEN_FOR_BLAS -I/scratch/cmsbuild/jenkins_b/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_ppc64le_gcc9/external/onnxruntime/1.6.0-6c793c0e805c69f27c5d43c22113bed0/onnxruntime-1.6.0/include/onnxruntime -I/scratch/cmsbuild/jenkins_b/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_ppc64le_gcc9/external/onnxruntime/1.6.0-6c793c0e805c69f27c5d43c22113bed0/onnxruntime-1.6.0/include/onnxruntime/core/session -I/scratch/cmsbuild/jenkins_b/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_ppc64le_gcc9/external/onnxruntime/1.6.0-6c793c0e805c69f27c5d43c22113bed0/onnxruntime-1.6.0/cmake/external/SafeInt -I/scratch/cmsbuild/jenkins_b/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_ppc64le_gcc9/external/onnxruntime/1.6.0-6c793c0e805c69f27c5d43c22113bed0/onnxruntime-1.6.0/cmake/external/optional-lite/include -I/scratch/cmsbuild/jenkins_b/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_ppc64le_gcc9/external/onnxruntime/1.6.0-6c793c0e805c69f27c5d43c22113bed0/onnxruntime-1.6.0/cmake/external/nsync/public -I. -I/scratch/cmsbuild/jenkins_b/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_ppc64le_gcc9/external/onnxruntime/1.6.0-6c793c0e805c69f27c5d43c22113bed0/onnxruntime-1.6.0/cmake/external/onnx -Iexternal/onnx -I/scratch/cmsbuild/jenkins_b/workspace/ib-run-pr-tests/testBuildDir/slc7_ppc64le_gcc9/external/protobuf/3.15.1-ljfedo/include -I/scratch/cmsbuild/jenkins_b/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_ppc64le_gcc9/external/onnxruntime/1.6.0-6c793c0e805c69f27c5d43c22113bed0/onnxruntime-1.6.0/cmake/external/flatbuffers/include -I/scratch/cmsbuild/jenkins_b/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_ppc64le_gcc9/external/onnxruntime/1.6.0-6c793c0e805c69f27c5d43c22113bed0/onnxruntime-1.6.0/onnxruntime -I/scratch/cmsbuild/jenkins_b/workspace/ib-run-pr-tests/testBuildDir/slc7_ppc64le_gcc9/external/cudnn/8.1.1.33-e758fb257eed5552a316ccde58ce7909/include -I/scratch/cmsbuild/jenkins_b/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_ppc64le_gcc9/external/onnxruntime/1.6.0-6c793c0e805c69f27c5d43c22113bed0/onnxruntime-1.6.0/cmake/external/eigen -I/cvmfs/cms-ib.cern.ch/nweek-02674/slc7_ppc64le_gcc9/external/cuda/11.2.2-eb6d9e158c825f784dacfebf9c090173/include -Wall -Wextra -ffunction-sections -fdata-sections -Wno-deprecated-copy -Wno-parentheses -O3 -DNDEBUG -DGSL_UNENFORCED_ON_CONTRACT_VIOLATION -fPIC   -Wno-reorder -Wno-error=sign-compare -std=gnu++14 -MD -MT CMakeFiles/onnxruntime_providers_cuda.dir/scratch/cmsbuild/jenkins_b/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_ppc64le_gcc9/external/onnxruntime/1.6.0-6c793c0e805c69f27c5d43c22113bed0/onnxruntime-1.6.0/onnxruntime/core/providers/cuda/cuda_fence.cc.o -MF CMakeFiles/onnxruntime_providers_cuda.dir/scratch/cmsbuild/jenkins_b/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_ppc64le_gcc9/external/onnxruntime/1.6.0-6c793c0e805c69f27c5d43c22113bed0/onnxruntime-1.6.0/onnxruntime/core/providers/cuda/cuda_fence.cc.o.d -o CMakeFiles/onnxruntime_providers_cuda.dir/scratch/cmsbuild/jenkins_b/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_ppc64le_gcc9/external/onnxruntime/1.6.0-6c793c0e805c69f27c5d43c22113bed0/onnxruntime-1.6.0/onnxruntime/core/providers/cuda/cuda_fence.cc.o -c /scratch/cmsbuild/jenkins_b/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_ppc64le_gcc9/external/onnxruntime/1.6.0-6c793c0e805c69f27c5d43c22113bed0/onnxruntime-1.6.0/onnxruntime/core/providers/cuda/cuda_fence.cc
In file included from /scratch/cmsbuild/jenkins_b/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_ppc64le_gcc9/external/onnxruntime/1.6.0-6c793c0e805c69f27c5d43c22113bed0/onnxruntime-1.6.0/onnxruntime/core/providers/cuda/cuda_common.h:5,
                 from /scratch/cmsbuild/jenkins_b/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_ppc64le_gcc9/external/onnxruntime/1.6.0-6c793c0e805c69f27c5d43c22113bed0/onnxruntime-1.6.0/onnxruntime/core/providers/cuda/cuda_fence.cc:4:
/scratch/cmsbuild/jenkins_b/workspace/ib-run-pr-tests/testBuildDir/BUILD/slc7_ppc64le_gcc9/external/onnxruntime/1.6.0-6c793c0e805c69f27c5d43c22113bed0/onnxruntime-1.6.0/onnxruntime/core/providers/cuda/cuda_pch.h:16:10: fatal error: cudnn.h: No such file or directory
   16 | #include <cudnn.h>
```

**Comment by hqucms** [comment]
> for ppc64le, onnxruntime failed to find `cudnn.h`. I do see that `-I/scratch/cmsbuild/jenkins_b/workspace/ib-run-pr-tests/testBuildDir/slc7_ppc64le_gcc9/external/cudnn/8.1.1.33-e758fb257eed5552a316ccde58ce7909/include` is there. Are cudnn header installed in different include path or may be there is a sub-directory?

Indeed. For the ppc64le tarball everything is under a sub-directory `targets/ppc64le-linux`.

**Comment by smuzaffar** [comment]
yes, I just noticed that. Can you move %{i}/targets/ppc64le-linux/* to %{i}/?

**Comment by smuzaffar** [comment]
@hqucms , for `ppc64le` the lib directory is called `lib` and on `aarch64` it is `lib64`. I would suggest that rename it to `lib64` for `ppc64le` too . This will avoid adding conditions in cudnn toolfile

**Comment by hqucms** [comment]
> @hqucms , for `ppc64le` the lib directory is called `lib` and on `aarch64` it is `lib64`. I would suggest that rename it to `lib64` for `ppc64le` too . This will avoid adding conditions in cudnn toolfile

@smuzaffar Sure will do!
For `aarch64` the failure is due to glibc version (cudnn requires 2.27). Any suggestions?

**Comment by hqucms** [comment]
please test for slc7_ppc64le_gcc9

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
please test for slc7_ppc64le_gcc9

**Comment by smuzaffar** [comment]
Looks like for aarch64 the cudnn is build with newer glibc 2.27 and failed to install due to missing `libm.so.6(GLIBC_2.27)(64bit)` . For CentOS7 , we have `glibc-2.17` which only provides `libm.so.6(GLIBC_2.17)(64bit)` . 

`libm.so.6(GLIBC_2.27)(64bit)` is available on CentOS8  as there we have newer glibc. Is there any other source for cc7/aarch64 cudnn  ?

**Comment by smuzaffar** [comment]
looks like cudnn for aarch64 is only supported for RHEL 8 ( https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html#cudnn-810-811-linux)

**Comment by hqucms** [comment]
> looks like cudnn for aarch64 is only supported for RHEL 8 ( https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html#cudnn-810-811-linux)

I just found the same page too:)
Shall we test with `cc8_aarch64_gcc9 ` then?

**Comment by smuzaffar** [comment]
yes we can test with cc8_aarch64_gcc9  but you still need to disable it for slc7_aarch64. You can use %{cmsos} to check for the this. cmsos should is arch string with the gccXXX part e.g for slc7_aarch64_gcc9 it should be slc7_aarch64.

**Comment by hqucms** [comment]
> yes we can test with cc8_aarch64_gcc9 but you still need to disable it for slc7_aarch64. You can use %{cmsos} to check for the this. cmsos should is arch string with the gccXXX part e.g for slc7_aarch64_gcc9 it should be slc7_aarch64.

Thank you @smuzaffar !
Let's test with cc8_aarch64_gcc9 and see how it goes:)

**Comment by hqucms** [comment]
please test for cc8_aarch64_gcc9

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmsdist/pull/6776#issuecomment-815075807  looks good, unit tests failure are not related to this PR. The onnxruntime unit test has already been fixed.

@hqucms , please update the PR to avoid including cudnn fopr slc7_aarch64

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
please test for slc7_ppc64le_gcc9

**Comment by hqucms** [comment]
please test for slc7_aarch64_gcc9

**Comment by hqucms** [comment]
please test for cc8_aarch64_gcc9

**Comment by hqucms** [comment]
@smuzaffar The unit test failures look unrelated to this PR?

**Comment by smuzaffar** [comment]
test parameters:
- enable_test = threading,gpu

**Comment by smuzaffar** [comment]
please test
yes @hqucms , unit tests failure are not related to this PR. Let me re-run it with threading on for production arch.

**Comment by hqucms** [comment]
> please test
> yes @hqucms , unit tests failure are not related to this PR. Let me re-run it with threading on for production arch.

Thank you for confirming @smuzaffar !
One thing I think would be useful to add is a unittest that tests ONNXRuntime on GPU. But I think it can be added after this PR is finalized?

**Comment by smuzaffar** [comment]
yes ONNXRuntime on GPU unit tests should be added to make sure the functionaly is working.
If you already have something to test then please go ahead and open cmssw pr.

**Comment by smuzaffar** [comment]
+externals
looks good to go in

**Comment by silviodonato** [comment]
+1
